### ISSUE TITLE
After a while working fine app stops work on non jailbroken iPhone 6 (iOS 10.3.1 and 10.3.2)

### ISSUE THREAD

**Issue by lcfrederico** [freemanrepo/cercube-for-youtube#2]
I noticed it for a while (at least since  v4.0.9.5). Then a need to use Cydia Impactor again to reinstall it.

**Comment by freemanrepo** [comment]
Cydia Impactor signing only allows you 7 days before you have to re-use Cydia Impactor again. I recommend using http://extensify.io.
